# -*- coding: utf-8 -*-
"""Another copy of Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J-3U89nApxjlzk0kADWa6rmS9VYv_QmT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**1. Read the dataset to python environment.**"""

data = pd.read_excel('/content/iris.xls')
data.head()

"""**2. Display the columns in the dataset.**"""

data.columns

"""**3. Calculate the mean of each column of the dataset**"""

data.mean()

"""**4. Check for the null values present in the dataset.**"""

data.isnull()

"""**5. visualization**"""

data = data

data.describe()

iris = sns.load_dataset('iris')

# Plot using Seaborn (pairplot)
sns.pairplot(iris, hue='species')
plt.title('Pairplot of Iris Dataset')
plt.show()